In [2]:
import numpy as np

In [26]:
mylis = ['a',2,3]
arr = np.array(mylis)

array

array(['a', '2', '3'], dtype='<U1')

In [7]:
mynewlis = [[1,2,78],[7,8,86]]
np.array(mynewlis)

array([[ 1,  2, 78],
       [ 7,  8, 86]])

In [11]:
try:
    import numpy
    print('numpy is imported')
except ImportError:
    print ("numpy is not installed")

numpy is imported


In [15]:
np.arange(0,8,2)

array([0, 2, 4, 6])

In [16]:
np.random.rand(5)

array([0.74759077, 0.44627816, 0.33063564, 0.32094379, 0.91397055])

In [17]:
np.random.rand(5,5)

array([[0.27151518, 0.04571952, 0.25013826, 0.50228362, 0.52524253],
       [0.63818104, 0.65930533, 0.8665845 , 0.98325044, 0.19690934],
       [0.67865665, 0.45037225, 0.40856401, 0.40386899, 0.07866248],
       [0.05232894, 0.66413991, 0.84571485, 0.95715231, 0.40673562],
       [0.68547727, 0.02055107, 0.46263045, 0.78899989, 0.90546457]])

In [27]:
arr.dtype

dtype('<U1')

In [24]:
arr.argmin()

0

In [29]:
from random import randint

In [45]:
import numpy as np
arr = np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [49]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr[0:5] = 12

In [51]:
arr

array([12, 12, 12, 12, 12,  5,  6,  7,  8,  9, 10])

In [52]:
arr = np.arange(0,11)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
slice_of_arr = arr[0:6]

In [58]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [56]:
slice_of_arr[:] = 99

In [57]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [60]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [61]:
arr_copy[:] = 2

In [62]:
arr_copy

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [63]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

##NumPy Indexing and Selection

In [66]:
arr_2nd = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [67]:
arr_2nd

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [86]:
arr_2nd[2,2], arr_2nd[1,2]

(45, 30)

In [88]:
arr_2nd[:2,1:]

array([[10, 15],
       [25, 30]])

In [125]:
arr = np.arange(0,12)
print (arr)
newarr = arr.reshape(3,4)
newarr

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
newarr = arr.reshape(3,4)
newarr[1:,:2]

array([[4, 5],
       [8, 9]])

In [96]:
arr[arr>=3]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

NumPy Operations

In [131]:
arr = np.arange(0,11)
arr/arr

C:\Users\Sanket\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [132]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])